[package]
name = "madaha"
version = "0.1.0"
edition = "2024"

[dependencies]
alsa = "0.11.0"
clap = {version="4.6.1", features=["derive", "env"]}
num_enum = "0.7.6"
opl3-rs = "0.2.3" # experimental fm synth for Synth Lead Instruments
serde = { version = "1.0.228", features = ["derive"] }
strum = "0.28.0"
strum_macros = "0.28.0"
toml = "1.1.2"
wd_log = "0.4.0"
cpal = "0.18.1"

[dependencies.libmadaha]
path = "libmadaha"
