const XGLITE_SUPPORT: [[bool; 128]; 128] = [
    /* LSB=  0 */ [true; 128],
    /* LSB=  1 */ [true; 128],
    /* LSB=  2 */ [true; 128],
    /* LSB=  3 */ [true; 128],
    /* LSB=  4 */ [true; 128],
    /* LSB=  5 */ [true; 128],
    /* LSB=  6 */ [true; 128],
    /* LSB=  7 */ [true; 128],
    /* LSB=  8,   1 fallbacks */
    [
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, false, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true,
    ],
    /* LSB=  9 */ [true; 128],
    /* LSB= 10 */ [true; 128],
    /* LSB= 11 */ [true; 128],
    /* LSB= 12,   1 fallbacks */
    [
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, false, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true,
    ],
    /* LSB= 13 */ [true; 128],
    /* LSB= 14,   1 fallbacks */
    [
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, false, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true,
    ],
    /* LSB= 15 */ [true; 128],
    /* LSB= 16,  32 fallbacks */
    [
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, false, false, false, false, false,
        false, false, false, false, false, false, false, false, false, false, false, false, false,
        false, false, false, false, false, false, false, false, false, false, false, true, true,
        true, false, true, false, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, false, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true,
    ],
    /* LSB= 17,   2 fallbacks */
    [
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, false, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, false,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true,
    ],
    /* LSB= 18,   5 fallbacks */
    [
        false, true, true, true, false, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, false, true, true, true,
        true, true, true, true, true, true, true, true, false, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, false,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true,
    ],
    /* LSB= 19 */ [true; 128],
    /* LSB= 20,   2 fallbacks */
    [
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, false, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, false, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true,
    ],
    /* LSB= 21 */ [true; 128],
    /* LSB= 22 */ [true; 128],
    /* LSB= 23 */ [true; 128],
    /* LSB= 24,   5 fallbacks */
    [
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, false, true, true, true, true, true, true,
        true, true, true, false, true, true, true, true, true, true, true, true, true, true, true,
        true, true, false, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, false, true, true, true, false, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true,
    ],
    /* LSB= 25,   3 fallbacks */
    [
        true, true, true, true, true, true, false, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, false, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, false, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true,
    ],
    /* LSB= 26 */ [true; 128],
    /* LSB= 27,   6 fallbacks */
    [
        true, true, true, true, true, true, true, false, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, false, true, true, false, true, true, true, true, true, true, true, true,
        true, true, true, true, true, false, true, true, true, true, true, true, true, true, true,
        true, true, false, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, false, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true,
    ],
    /* LSB= 28 */ [true; 128],
    /* LSB= 29 */ [true; 128],
    /* LSB= 30 */ [true; 128],
    /* LSB= 31 */ [true; 128],
    /* LSB= 32,   4 fallbacks */
    [
        true, true, true, true, true, false, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, false, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, false, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, false, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true,
    ],
    /* LSB= 33,   1 fallbacks */
    [
        true, true, true, true, true, false, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true,
    ],
    /* LSB= 34,   1 fallbacks */
    [
        true, true, true, true, true, false, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true,
    ],
    /* LSB= 35,   1 fallbacks */
    [
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, false, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true,
    ],
    /* LSB= 36,   1 fallbacks */
    [
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, false, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true,
    ],
    /* LSB= 37 */ [true; 128],
    /* LSB= 38,   1 fallbacks */
    [
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, false, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true,
    ],
    /* LSB= 39 */ [true; 128],
    /* LSB= 40,   8 fallbacks */
    [
        true, true, false, false, false, false, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, false, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, false, true, false, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, false, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true,
    ],
    /* LSB= 41,   4 fallbacks */
    [
        true, true, false, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, false, true, true, true, true, false, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, false, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true,
    ],
    /* LSB= 42,   2 fallbacks */
    [
        true, true, true, true, true, false, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, false, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true,
    ],
    /* LSB= 43,   2 fallbacks */
    [
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, false, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, false, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true,
    ],
    /* LSB= 44 */ [true; 128],
    /* LSB= 45,   7 fallbacks */
    [
        true, true, true, true, false, false, true, true, true, true, true, false, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, false, false, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, false, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, false, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true,
    ],
    /* LSB= 46 */ [true; 128],
    /* LSB= 47 */ [true; 128],
    /* LSB= 48 */ [true; 128],
    /* LSB= 49 */ [true; 128],
    /* LSB= 50 */ [true; 128],
    /* LSB= 51 */ [true; 128],
    /* LSB= 52 */ [true; 128],
    /* LSB= 53 */ [true; 128],
    /* LSB= 54 */ [true; 128],
    /* LSB= 55 */ [true; 128],
    /* LSB= 56 */ [true; 128],
    /* LSB= 57 */ [true; 128],
    /* LSB= 58 */ [true; 128],
    /* LSB= 59 */ [true; 128],
    /* LSB= 60 */ [true; 128],
    /* LSB= 61 */ [true; 128],
    /* LSB= 62 */ [true; 128],
    /* LSB= 63 */ [true; 128],
    /* LSB= 64,  15 fallbacks */
    [
        true, true, true, true, false, true, true, false, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, false, false, true, true, true, true, true,
        true, true, true, true, false, false, false, true, true, true, true, true, true, true,
        true, true, true, false, false, true, true, false, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, false, true, false, true, true,
        true, true, true, true, true, true, false, true, true, true, true, true, true, false, true,
        true, true, true, true, true, true, true, true, false, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true,
    ],
    /* LSB= 65,   9 fallbacks */
    [
        true, true, true, true, true, true, true, false, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, false, true, true, true, true, true, true,
        true, true, true, true, false, false, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, false, true, true, true, true, false,
        false, false, true, true, true, true, true, true, true, true, true, true, false, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true,
    ],
    /* LSB= 66,   6 fallbacks */
    [
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, false, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        false, true, true, true, true, false, true, true, false, true, true, false, false, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true,
    ],
    /* LSB= 67,   9 fallbacks */
    [
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        false, false, false, false, false, false, false, false, true, true, true, true, false,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true,
    ],
    /* LSB= 68,   2 fallbacks */
    [
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, false, true, true, true, false, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true,
    ],
    /* LSB= 69,   2 fallbacks */
    [
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, false, true, true, true, false, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true,
    ],
    /* LSB= 70 */ [true; 128],
    /* LSB= 71 */ [true; 128],
    /* LSB= 72 */ [true; 128],
    /* LSB= 73 */ [true; 128],
    /* LSB= 74 */ [true; 128],
    /* LSB= 75 */ [true; 128],
    /* LSB= 76 */ [true; 128],
    /* LSB= 77 */ [true; 128],
    /* LSB= 78 */ [true; 128],
    /* LSB= 79 */ [true; 128],
    /* LSB= 80 */ [true; 128],
    /* LSB= 81 */ [true; 128],
    /* LSB= 82 */ [true; 128],
    /* LSB= 83 */ [true; 128],
    /* LSB= 84 */ [true; 128],
    /* LSB= 85 */ [true; 128],
    /* LSB= 86 */ [true; 128],
    /* LSB= 87 */ [true; 128],
    /* LSB= 88 */ [true; 128],
    /* LSB= 89 */ [true; 128],
    /* LSB= 90 */ [true; 128],
    /* LSB= 91 */ [true; 128],
    /* LSB= 92 */ [true; 128],
    /* LSB= 93 */ [true; 128],
    /* LSB= 94 */ [true; 128],
    /* LSB= 95 */ [true; 128],
    /* LSB= 96,   5 fallbacks */
    [
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, false, true, true, false, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, false, true, true, true, false,
        true, true, true, true, true, true, false, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true,
    ],
    /* LSB= 97,   2 fallbacks */
    [
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, false, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, false, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true,
    ],
    /* LSB= 98 */ [true; 128],
    /* LSB= 99 */ [true; 128],
    /* LSB=100 */ [true; 128],
    /* LSB=101,   1 fallbacks */
    [
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, false, true, true, true, true, true, true, true,
        true, true, true, true, true, true, true, true,
    ],
    /* LSB=102 */ [true; 128],
    /* LSB=103 */ [true; 128],
    /* LSB=104 */ [true; 128],
    /* LSB=105 */ [true; 128],
    /* LSB=106 */ [true; 128],
    /* LSB=107 */ [true; 128],
    /* LSB=108 */ [true; 128],
    /* LSB=109 */ [true; 128],
    /* LSB=110 */ [true; 128],
    /* LSB=111 */ [true; 128],
    /* LSB=112 */ [true; 128],
    /* LSB=113 */ [true; 128],
    /* LSB=114 */ [true; 128],
    /* LSB=115 */ [true; 128],
    /* LSB=116 */ [true; 128],
    /* LSB=117 */ [true; 128],
    /* LSB=118 */ [true; 128],
    /* LSB=119 */ [true; 128],
    /* LSB=120 */ [true; 128],
    /* LSB=121 */ [true; 128],
    /* LSB=122 */ [true; 128],
    /* LSB=123 */ [true; 128],
    /* LSB=124 */ [true; 128],
    /* LSB=125 */ [true; 128],
    /* LSB=126 */ [true; 128],
    /* LSB=127 */ [true; 128],
];

pub fn map_xg_lite(lsb: u8, prog: u8) -> usize {
    if XGLITE_SUPPORT[lsb as usize][prog as usize] {
        lsb as usize
    } else {
        0usize
    }
}
