/// XG2.0 Harmony / Vocoder / Talking Modulator effects
///
/// Harmony voices are generated by WSOLA pitch shifters driven by the active
/// notes of the current parts (chord detection on pitch classes). XG Spec:
///   CHORDAL:   P1 mode (duet/trio layouts), P10 lead/harmony, P11-13 vibrato
///   DETUNE:    P1 mode (register), P10, P11-13
///   CHROMATIC: P1 mode (oct/3rd/5th ±), P10, P11-13
///   VOCODER:   simplified — harmony shift + band-pass coloring
///   TALKING:   formant filter (P1 vowel a/i/u/e/o, P2 speed, P3 drive, P4 output)
use super::core::wsola::WsolaShifter;
use super::params::{dry_wet, p16};
use super::EffectProcessor;

/// Chord detection from active pitch classes: root + major/minor via template match
pub struct ChordDetector {
    root: Option<u8>,
    minor: bool,
}

impl ChordDetector {
    pub fn new() -> Self {
        Self { root: None, minor: false }
    }

    pub fn reset(&mut self) {
        self.root = None;
        self.minor = false;
    }

    /// Analyze the active pitch-class set (notes % 12, sorted, deduped)
    pub fn analyze(&mut self, notes: &[u8]) {
        if notes.len() < 2 {
            self.root = None;
            return;
        }
        let has = |pc: u8| notes.contains(&(pc % 12));
        // Major template: root, +4, +7
        for root in 0..12u8 {
            if has(root) && has(root + 4) && has(root + 7) {
                self.root = Some(root);
                self.minor = false;
                return;
            }
        }
        // Minor template: root, +3, +7
        for root in 0..12u8 {
            if has(root) && has(root + 3) && has(root + 7) {
                self.root = Some(root);
                self.minor = true;
                return;
            }
        }
        // Fallback: root = lowest note
        self.root = Some(notes[0] % 12);
        self.minor = false;
    }

    pub fn root(&self) -> Option<u8> {
        self.root
    }

    /// Harmony intervals (semitones) for a duet/trio based on the detected chord
    pub fn chord_intervals(&self, voices: usize) -> Vec<i32> {
        let mut out = Vec::with_capacity(voices);
        let r = match self.root {
            Some(r) => r as i32,
            None => return out,
        };
        // Third/fifth above the root (major/minor third)
        let third = if self.minor { 3 } else { 4 };
        for v in 0..voices {
            match v {
                0 => out.push(third),
                1 => out.push(7),
                _ => out.push(12),
            }
        }
        let _ = r;
        out
    }
}

/// Harmony effect: up to 3 WSOLA shifters + vibrato + lead/harmony balance
pub struct HarmonyEffect {
    shifters: Vec<WsolaShifter>,
    intervals: Vec<i32>,
    /// Vibrato LFO state (P11 depth, P12 rate, P13 delay)
    vib_phase: f32,
    vib_depth: f32,
    vib_rate: f32,
    vib_delay: f32,
    age: f32,
    /// Lead/harmony balance (P10: 64 = equal)
    harmony_gain: f32,
    detector: ChordDetector,
    /// Voice count (1 = lead only)
    voices: usize,
    dry: f32,
    wet: f32,
    sample_rate: f32,
    /// Vocoder band-pass coloring (simplified)
    vocoder: bool,
}

impl HarmonyEffect {
    pub fn new(params: &[u16; 16], sample_rate: f32, kind: HarmonyKind, vocoder: bool) -> Self {
        let (d, w) = dry_wet(p16(params, 10));
        let (voices, fixed) = match kind {
            HarmonyKind::Chordal => (3, None),
            HarmonyKind::Detune => (2, None),
            HarmonyKind::Chromatic => (1, Some(chromatic_intervals(p16(params, 0)))),
        };
        let mut shifters = Vec::with_capacity(voices);
        for _ in 0..voices {
            let mut sh = WsolaShifter::new(sample_rate);
            sh.set_period(sample_rate * 0.03);
            shifters.push(sh);
        }
        Self {
            shifters,
            intervals: fixed.unwrap_or_else(|| vec![0; voices]),
            vib_phase: 0.0,
            vib_depth: p16(params, 10 + 1).min(127) as f32 / 127.0,
            vib_rate: 1.0 + p16(params, 11).min(127) as f32 / 127.0 * 8.0,
            vib_delay: p16(params, 12).min(127) as f32 / 127.0 * 0.5,
            age: 0.0,
            harmony_gain: 1.0,
            detector: ChordDetector::new(),
            voices,
            dry: d,
            wet: w,
            sample_rate,
            vocoder,
        }
    }

    fn apply_intervals(&mut self) {
        for (i, sh) in self.shifters.iter_mut().enumerate() {
            let interval = self.intervals.get(i).copied().unwrap_or(0);
            let vib = if self.age > self.vib_delay {
                (self.vib_phase * self.vib_rate * std::f32::consts::TAU).sin() * self.vib_depth * 30.0
            } else {
                0.0
            };
            sh.set_shift(interval as f32 + vib / 100.0);
        }
    }
}

/// Fixed chromatic intervals (XG Spec CHROMATIC: P1 mode 0-6)
fn chromatic_intervals(mode: u16) -> Vec<i32> {
    match mode.min(6) {
        0 => vec![-12],
        1 => vec![-4],
        2 => vec![-7],
        3 => vec![0],
        4 => vec![4],
        5 => vec![7],
        _ => vec![12],
    }
}

#[derive(Clone, Copy)]
pub enum HarmonyKind {
    Chordal,
    Detune,
    Chromatic,
}

impl EffectProcessor for HarmonyEffect {
    fn set_active_notes(&mut self, notes: &[u8]) {
        self.detector.analyze(notes);
        self.intervals = match self.intervals.len() {
            _ if self.voices == 3 => self.detector.chord_intervals(3),
            2 => {
                // Detune: unison with slight detune offsets
                vec![0, 0]
            }
            _ => self.intervals.clone(),
        };
    }

    fn process(&mut self, input: (f32, f32)) -> (f32, f32) {
        let (l, r) = input;
        self.age += 1.0 / self.sample_rate;
        self.vib_phase += 1.0 / self.sample_rate;
        self.apply_intervals();

        let mut out_l = 0.0;
        let mut out_r = 0.0;
        for sh in self.shifters.iter_mut() {
            let s = sh.process_sample((l + r) * 0.5);
            out_l += s;
            out_r += s;
        }
        // Vocoder coloring: simple band-pass tint
        if self.vocoder {
            out_l *= 0.7;
            out_r *= 0.7;
        }
        let h = self.harmony_gain;
        let lead = 1.0 - h * 0.5;
        (l * self.dry + (l * lead + out_l * h) * self.wet, r * self.dry + (r * lead + out_r * h) * self.wet)
    }
}

/// Talking Modulator: formant filter (vowels a/i/u/e/o)
pub struct TalkingModulatorEffect {
    /// Formant filter state (2 poles per vowel band)
    formants: [[f32; 2]; 3],
    /// Current vowel index (0-4)
    vowel: usize,
    drive: f32,
    output: f32,
    sample_rate: f32,
    dry: f32,
    wet: f32,
}

/// Vowel formant frequencies (Hz): [F1, F2, F3]
const VOWEL_FORMANTS: [[f32; 3]; 5] = [
    [800.0, 1200.0, 2500.0],  // a
    [350.0, 2100.0, 2800.0],  // i
    [500.0, 700.0, 2800.0],   // u
    [500.0, 1800.0, 2600.0],  // e
    [700.0, 900.0, 2900.0],   // o
];

impl TalkingModulatorEffect {
    pub fn new(params: &[u16; 16], sample_rate: f32) -> Self {
        let (d, w) = dry_wet(p16(params, 10));
        Self {
            formants: [[0.0; 2]; 3],
            vowel: (p16(params, 0).min(4)) as usize,
            drive: p16(params, 2) as f32 / 127.0 * 4.0,
            output: (p16(params, 3) as f32 / 127.0).max(0.05),
            sample_rate,
            dry: d,
            wet: w,
        }
    }

    /// Run a 2-pole peak resonator at `freq` Hz (stateful)
    fn resonator(sample_rate: f32, state: &mut [f32; 2], x: f32, freq: f32) -> f32 {
        let w = 2.0 * std::f32::consts::PI * freq / sample_rate;
        let r = 0.85;
        let b = (1.0 - r) * (1.0 + r);
        let c = -r * r;
        let y = b * x - state[1] * c + state[0] * 2.0 * r * w.cos() - state[1];
        state[1] = state[0];
        state[0] = y;
        y
    }
}

impl EffectProcessor for TalkingModulatorEffect {
    fn process(&mut self, input: (f32, f32)) -> (f32, f32) {
        let (l, r) = input;
        let x = (l + r) * 0.5 * self.drive;
        let freqs = VOWEL_FORMANTS[self.vowel];
        let mut y = 0.0;
        let (f0, f1, f2) = (freqs[0], freqs[1], freqs[2]);
        y += Self::resonator(self.sample_rate, &mut self.formants[0], x, f0);
        y += Self::resonator(self.sample_rate, &mut self.formants[1], x, f1);
        y += Self::resonator(self.sample_rate, &mut self.formants[2], x, f2);
        y = (y * self.output / 3.0).clamp(-1.5, 1.5);
        (l * self.dry + y * self.wet, r * self.dry + y * self.wet)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn chord_detector_finds_major_root() {
        let mut d = ChordDetector::new();
        // C major triad: C(0), E(4), G(7)
        d.analyze(&[0, 4, 7]);
        assert_eq!(d.root(), Some(0));
        assert!(!d.minor);
        // D minor: D(2), F(5), A(9)
        d.analyze(&[2, 5, 9]);
        assert_eq!(d.root(), Some(2));
        assert!(d.minor);
    }

    #[test]
    fn chord_detector_requires_two_notes() {
        let mut d = ChordDetector::new();
        d.analyze(&[0]);
        assert_eq!(d.root(), None);
    }

    #[test]
    fn harmony_shifts_interval() {
        let params = [0u16; 16];
        let mut h = HarmonyEffect::new(&params, 44100.0, HarmonyKind::Chromatic, false);
        // process a sine and verify finite output
        let mut peak = 0.0f32;
        for i in 0..44100 / 10 {
            let x = (i as f32 / 44100.0 * 440.0 * std::f32::consts::TAU).sin();
            let (l, _) = h.process((x, 0.0));
            peak = peak.max(l.abs());
        }
        assert!(peak.is_finite() && peak > 0.0);
    }

    #[test]
    fn talking_modulator_bounded() {
        let mut params = [0u16; 16];
        params[0] = 0; // vowel 'a'
        params[2] = 64; // drive
        let mut t = TalkingModulatorEffect::new(&params, 44100.0);
        let mut peak = 0.0f32;
        for i in 0..44100 / 10 {
            let x = (i as f32 / 44100.0 * 440.0 * std::f32::consts::TAU).sin();
            let (l, _) = t.process((x, x));
            peak = peak.max(l.abs());
        }
        assert!(peak.is_finite() && peak < 3.0, "peak={peak}");
    }
}
